# Generated by Django 4.1.5 on 2023-08-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
                ('batch', models.CharField(max_length=264)),
            ],
        ),
    ]
