# Generated by Django 4.1.5 on 2023-08-15 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='student1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
                ('batch', models.CharField(max_length=264)),
                ('vision', models.CharField(max_length=264)),
                ('mission', models.CharField(max_length=264)),
                ('peo', models.CharField(max_length=264)),
                ('pos', models.CharField(max_length=264)),
            ],
        ),
    ]
