# Generated by Django 4.1.5 on 2023-08-15 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mission',
        ),
        migrations.RemoveField(
            model_name='student',
            name='peos',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pso',
        ),
        migrations.RemoveField(
            model_name='student',
            name='vision',
        ),
    ]
