# Generated by Django 4.1.5 on 2023-08-15 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_student_mission_remove_student_peos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='student1',
            options={'managed': False},
        ),
    ]
