# Generated by Django 4.1.5 on 2023-08-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_staff1'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.TextField()),
                ('staff_email', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('peo', models.TextField()),
                ('pos', models.TextField()),
            ],
        ),
    ]
