import pyautogui
import time
pyautogui.keyDown('win')
pyautogui.keyDown('ctrl')
pyautogui.press('right')
pyautogui.keyUp('win')
pyautogui.keyUp('ctrl')
time.sleep(1)
pyautogui.keyDown('win')
pyautogui.press('r')
pyautogui.keyUp('win')
time.sleep(1)
pyautogui.press('enter')
time.sleep(2)
pyautogui.write('cd new\Scripts')
time.sleep(1)
pyautogui.press('enter')
time.sleep(1)
pyautogui.write('activate')
pyautogui.press('enter')

time.sleep(1)
pyautogui.write('cd ..')
pyautogui.press('enter')
pyautogui.write('cd ..')
pyautogui.press('enter')
time.sleep(1)
pyautogui.write('cd OneDrive\Desktop\college')
pyautogui.press('enter')
pyautogui.write('python manage.py runserver')
pyautogui.press('enter')